// Mock data for demo mode
// This data is returned by server actions when in demo mode

export const DEMO_ORG_ID = "demo-org-id";
export const DEMO_USER_ID = "demo-user-id";

// Demo Recipients
export const demoRecipients = [
  {
    id: "demo-recipient-1",
    email: "sarah.johnson@techcorp.com",
    firstName: "Sarah",
    lastName: "Johnson",
    phone: "+1 (555) 123-4567",
    company: "TechCorp Inc",
    jobTitle: "VP of Engineering",
    linkedinUrl: "https://linkedin.com/in/sarahjohnson",
    address: JSON.stringify({ street: "123 Tech Blvd", city: "San Francisco", state: "CA", zip: "94105", country: "USA" }),
    notes: "Met at SaaStr conference. Interested in Q2 rollout.",
    tags: "enterprise,hot-lead,tech",
    organizationId: DEMO_ORG_ID,
    doNotSend: false,
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: "demo-recipient-2",
    email: "michael.chen@startupxyz.io",
    firstName: "Michael",
    lastName: "Chen",
    phone: "+1 (555) 234-5678",
    company: "StartupXYZ",
    jobTitle: "CEO & Founder",
    linkedinUrl: "https://linkedin.com/in/michaelchen",
    address: JSON.stringify({ street: "456 Innovation Way", city: "Austin", state: "TX", zip: "78701", country: "USA" }),
    notes: "Series A company, 50 employees. Decision maker.",
    tags: "startup,decision-maker,series-a",
    organizationId: DEMO_ORG_ID,
    doNotSend: false,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    id: "demo-recipient-3",
    email: "emily.rodriguez@globalsales.com",
    firstName: "Emily",
    lastName: "Rodriguez",
    phone: "+1 (555) 345-6789",
    company: "Global Sales Corp",
    jobTitle: "Director of Procurement",
    linkedinUrl: "https://linkedin.com/in/emilyrodriguez",
    address: JSON.stringify({ street: "789 Corporate Plaza", city: "New York", state: "NY", zip: "10001", country: "USA" }),
    notes: "Looking for gifting solution for 200+ sales reps.",
    tags: "enterprise,procurement,high-value",
    organizationId: DEMO_ORG_ID,
    doNotSend: false,
    createdAt: new Date("2024-10-20"),
    updatedAt: new Date("2025-01-20"),
  },
  {
    id: "demo-recipient-4",
    email: "david.kim@financeplus.com",
    firstName: "David",
    lastName: "Kim",
    phone: "+1 (555) 456-7890",
    company: "Finance Plus",
    jobTitle: "Head of Sales",
    linkedinUrl: "https://linkedin.com/in/davidkim",
    address: JSON.stringify({ street: "321 Wall Street", city: "Chicago", state: "IL", zip: "60601", country: "USA" }),
    notes: "Previous customer at old company. Very warm lead.",
    tags: "warm-lead,finance,returning",
    organizationId: DEMO_ORG_ID,
    doNotSend: false,
    createdAt: new Date("2024-09-05"),
    updatedAt: new Date("2025-01-18"),
  },
  {
    id: "demo-recipient-5",
    email: "jessica.taylor@medtech.health",
    firstName: "Jessica",
    lastName: "Taylor",
    phone: "+1 (555) 567-8901",
    company: "MedTech Health",
    jobTitle: "Chief Revenue Officer",
    linkedinUrl: "https://linkedin.com/in/jessicataylor",
    address: JSON.stringify({ street: "555 Healthcare Dr", city: "Boston", state: "MA", zip: "02101", country: "USA" }),
    notes: "Healthcare sector. Compliance-sensitive.",
    tags: "healthcare,cro,enterprise",
    organizationId: DEMO_ORG_ID,
    doNotSend: false,
    createdAt: new Date("2024-08-12"),
    updatedAt: new Date("2025-01-22"),
  },
];

// Demo Gift Categories
export const demoGiftCategories = [
  {
    id: "demo-category-1",
    name: "Tech Gadgets",
    description: "Latest tech accessories and gadgets",
    icon: "Laptop",
    color: "#3B82F6",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "demo-category-2",
    name: "Food & Wine",
    description: "Gourmet food baskets and wine selections",
    icon: "Wine",
    color: "#EF4444",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "demo-category-3",
    name: "Experiences",
    description: "Memorable experiences and activities",
    icon: "Ticket",
    color: "#10B981",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "demo-category-4",
    name: "Office Essentials",
    description: "Premium office supplies and accessories",
    icon: "Briefcase",
    color: "#8B5CF6",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

// Demo Gift Items
export const demoGiftItems = [
  {
    id: "demo-gift-1",
    name: "Premium Wireless Earbuds",
    description: "High-quality wireless earbuds with noise cancellation and 24-hour battery life.",
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400",
    price: 149.99,
    currency: "USD",
    categoryId: "demo-category-1",
    type: "PHYSICAL",
    inStock: true,
    isActive: true,
    tags: "tech,audio,popular",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "demo-gift-2",
    name: "Artisan Coffee Gift Set",
    description: "Curated selection of premium single-origin coffees with a ceramic pour-over set.",
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400",
    price: 89.99,
    currency: "USD",
    categoryId: "demo-category-2",
    type: "PHYSICAL",
    inStock: true,
    isActive: true,
    tags: "coffee,food,popular",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "demo-gift-3",
    name: "Wine Tasting Experience",
    description: "Private wine tasting for two at a local vineyard with sommelier guidance.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400",
    price: 299.99,
    currency: "USD",
    categoryId: "demo-category-3",
    type: "EXPERIENCE",
    duration: "3 hours",
    location: "Various locations",
    inStock: true,
    isActive: true,
    tags: "wine,experience,luxury",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "demo-gift-4",
    name: "Leather Portfolio & Pen Set",
    description: "Handcrafted Italian leather portfolio with a premium fountain pen.",
    imageUrl: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
    price: 175.00,
    currency: "USD",
    categoryId: "demo-category-4",
    type: "PHYSICAL",
    inStock: true,
    isActive: true,
    tags: "office,leather,executive",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "demo-gift-5",
    name: "Gourmet Chocolate Collection",
    description: "24-piece assorted artisan chocolates from around the world.",
    imageUrl: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400",
    price: 65.00,
    currency: "USD",
    categoryId: "demo-category-2",
    type: "PHYSICAL",
    inStock: true,
    isActive: true,
    tags: "chocolate,food,gift",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "demo-gift-6",
    name: "Smart Desk Lamp",
    description: "LED desk lamp with wireless charging pad and adjustable color temperature.",
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400",
    price: 129.99,
    currency: "USD",
    categoryId: "demo-category-1",
    type: "PHYSICAL",
    inStock: true,
    isActive: true,
    tags: "tech,office,popular",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-04-01"),
  },
];

// Demo Campaigns
export const demoCampaigns = [
  {
    id: "demo-campaign-1",
    name: "Q1 Enterprise Outreach",
    description: "Gift campaign targeting enterprise decision makers for Q1 pipeline.",
    status: "ACTIVE",
    type: "MANUAL",
    budgetAmount: 5000,
    budgetSpent: 2150,
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-03-31"),
    organizationId: DEMO_ORG_ID,
    createdById: DEMO_USER_ID,
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2025-01-20"),
  },
  {
    id: "demo-campaign-2",
    name: "Customer Appreciation",
    description: "Thank you gifts for top customers from last year.",
    status: "COMPLETED",
    type: "MANUAL",
    budgetAmount: 3000,
    budgetSpent: 2875,
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    organizationId: DEMO_ORG_ID,
    createdById: DEMO_USER_ID,
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2025-01-05"),
  },
  {
    id: "demo-campaign-3",
    name: "Conference Follow-up",
    description: "Personalized gifts for leads met at SaaStr Annual.",
    status: "DRAFT",
    type: "MANUAL",
    budgetAmount: 2500,
    budgetSpent: 0,
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-28"),
    organizationId: DEMO_ORG_ID,
    createdById: DEMO_USER_ID,
    createdAt: new Date("2025-01-18"),
    updatedAt: new Date("2025-01-18"),
  },
];

// Demo Sends
export const demoSends = [
  {
    id: "demo-send-1",
    recipientId: "demo-recipient-1",
    giftItemId: "demo-gift-1",
    campaignId: "demo-campaign-1",
    userId: DEMO_USER_ID,
    type: "GIFT",
    status: "DELIVERED",
    message: "Sarah, loved meeting you at SaaStr! Here's a little something to make your commute better.",
    itemCost: 149.99,
    shippingCost: 12.00,
    totalCost: 161.99,
    sentAt: new Date("2025-01-10"),
    deliveredAt: new Date("2025-01-14"),
    trackingNumber: "1Z999AA10123456784",
    carrier: "UPS",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-14"),
  },
  {
    id: "demo-send-2",
    recipientId: "demo-recipient-2",
    giftItemId: "demo-gift-2",
    campaignId: "demo-campaign-1",
    userId: DEMO_USER_ID,
    type: "GIFT",
    status: "SHIPPED",
    message: "Michael, congrats on the Series A! Fuel for the long days ahead.",
    itemCost: 89.99,
    shippingCost: 8.00,
    totalCost: 97.99,
    sentAt: new Date("2025-01-18"),
    trackingNumber: "1Z999AA10123456785",
    carrier: "FedEx",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2025-01-17"),
    updatedAt: new Date("2025-01-18"),
  },
  {
    id: "demo-send-3",
    recipientId: "demo-recipient-3",
    giftItemId: "demo-gift-3",
    campaignId: "demo-campaign-1",
    userId: DEMO_USER_ID,
    type: "EXPERIENCE",
    status: "PROCESSING",
    message: "Emily, would love to treat you and a guest to a wine tasting. Let's discuss how we can help your team!",
    itemCost: 299.99,
    shippingCost: 0,
    totalCost: 299.99,
    scheduledAt: new Date("2025-02-01"),
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-20"),
  },
  {
    id: "demo-send-4",
    recipientId: "demo-recipient-4",
    giftItemId: "demo-gift-4",
    campaignId: "demo-campaign-2",
    userId: DEMO_USER_ID,
    type: "GIFT",
    status: "DELIVERED",
    message: "David, thanks for being such a great partner this year!",
    itemCost: 175.00,
    shippingCost: 15.00,
    totalCost: 190.00,
    sentAt: new Date("2024-12-18"),
    deliveredAt: new Date("2024-12-22"),
    trackingNumber: "1Z999AA10123456786",
    carrier: "UPS",
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-12-16"),
    updatedAt: new Date("2024-12-22"),
  },
  {
    id: "demo-send-5",
    recipientId: "demo-recipient-5",
    giftItemId: null,
    campaignId: null,
    userId: DEMO_USER_ID,
    type: "HANDWRITTEN_NOTE",
    status: "PENDING",
    message: "Jessica, it was great connecting at the healthcare summit. Looking forward to exploring how we can support MedTech Health's growth!",
    itemCost: 25.00,
    shippingCost: 5.00,
    totalCost: 30.00,
    scheduledAt: new Date("2025-01-28"),
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2025-01-22"),
    updatedAt: new Date("2025-01-22"),
  },
];

// Demo Budgets
export const demoBudgets = [
  {
    id: "demo-budget-1",
    name: "Q1 2025 Gifting Budget",
    type: "QUARTERLY",
    amount: 10000,
    spent: 2150,
    currency: "USD",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-03-31"),
    alertThreshold: 80,
    alertSent: false,
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2025-01-20"),
  },
  {
    id: "demo-budget-2",
    name: "Annual Executive Gifts",
    type: "ANNUAL",
    amount: 25000,
    spent: 8500,
    currency: "USD",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-12-31"),
    alertThreshold: 75,
    alertSent: false,
    organizationId: DEMO_ORG_ID,
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2025-01-15"),
  },
];

// Demo Activities
export const demoActivities = [
  {
    id: "demo-activity-1",
    type: "SEND_DELIVERED",
    subject: "Gift delivered to Sarah Johnson",
    description: "Premium Wireless Earbuds delivered successfully",
    organizationId: DEMO_ORG_ID,
    userId: DEMO_USER_ID,
    recipientId: "demo-recipient-1",
    sendId: "demo-send-1",
    createdAt: new Date("2025-01-14T14:30:00"),
    updatedAt: new Date("2025-01-14T14:30:00"),
  },
  {
    id: "demo-activity-2",
    type: "SEND_SHIPPED",
    subject: "Gift shipped to Michael Chen",
    description: "Artisan Coffee Gift Set shipped via FedEx",
    organizationId: DEMO_ORG_ID,
    userId: DEMO_USER_ID,
    recipientId: "demo-recipient-2",
    sendId: "demo-send-2",
    createdAt: new Date("2025-01-18T10:15:00"),
    updatedAt: new Date("2025-01-18T10:15:00"),
  },
  {
    id: "demo-activity-3",
    type: "SEND_CREATED",
    subject: "Experience booked for Emily Rodriguez",
    description: "Wine Tasting Experience scheduled for February",
    organizationId: DEMO_ORG_ID,
    userId: DEMO_USER_ID,
    recipientId: "demo-recipient-3",
    sendId: "demo-send-3",
    createdAt: new Date("2025-01-20T09:00:00"),
    updatedAt: new Date("2025-01-20T09:00:00"),
  },
  {
    id: "demo-activity-4",
    type: "RECIPIENT_ADDED",
    subject: "New recipient added",
    description: "Jessica Taylor from MedTech Health added to recipients",
    organizationId: DEMO_ORG_ID,
    userId: DEMO_USER_ID,
    recipientId: "demo-recipient-5",
    sendId: null,
    createdAt: new Date("2025-01-22T11:45:00"),
    updatedAt: new Date("2025-01-22T11:45:00"),
  },
  {
    id: "demo-activity-5",
    type: "CAMPAIGN_CREATED",
    subject: "New campaign created",
    description: "Conference Follow-up campaign created",
    organizationId: DEMO_ORG_ID,
    userId: DEMO_USER_ID,
    recipientId: null,
    sendId: null,
    createdAt: new Date("2025-01-18T16:20:00"),
    updatedAt: new Date("2025-01-18T16:20:00"),
  },
];

// Demo Task Decks
export const demoTaskDecks = [
  {
    id: "demo-deck-1",
    name: "Q1 Enterprise Outreach",
    description: "High-priority enterprise prospects for Q1",
    coverColor: "#3B82F6",
    emoji: "🎯",
    status: "SEALED",
    openedAt: null,
    completedAt: null,
    totalTasks: 3,
    completedTasks: 0,
    skippedTasks: 0,
    sourceType: "campaign",
    sourceId: "demo-campaign-1",
    organizationId: DEMO_ORG_ID,
    createdById: DEMO_USER_ID,
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-20"),
  },
  {
    id: "demo-deck-2",
    name: "Conference Follow-ups",
    description: "People we met at SaaStr",
    coverColor: "#10B981",
    emoji: "🤝",
    status: "OPENED",
    openedAt: new Date("2025-01-22"),
    completedAt: null,
    totalTasks: 2,
    completedTasks: 1,
    skippedTasks: 0,
    sourceType: "manual",
    sourceId: null,
    organizationId: DEMO_ORG_ID,
    createdById: DEMO_USER_ID,
    createdAt: new Date("2025-01-18"),
    updatedAt: new Date("2025-01-25"),
  },
  {
    id: "demo-deck-3",
    name: "Customer Appreciation",
    description: "Thank you notes for top customers",
    coverColor: "#8B5CF6",
    emoji: "💜",
    status: "COMPLETED",
    openedAt: new Date("2025-01-10"),
    completedAt: new Date("2025-01-15"),
    totalTasks: 5,
    completedTasks: 4,
    skippedTasks: 1,
    sourceType: "manual",
    sourceId: null,
    organizationId: DEMO_ORG_ID,
    createdById: DEMO_USER_ID,
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-15"),
  },
];

// Demo Outreach Tasks
export const demoOutreachTasks = [
  {
    id: "demo-task-1",
    recipientId: "demo-recipient-1",
    taskType: "VIDEO",
    title: "Record personalized intro video",
    description: "Create a 60-second video mentioning their recent product launch and how our solution can help scale their engineering team.",
    context: JSON.stringify({
      talkingPoints: ["Met at SaaStr conference", "VP of Engineering at TechCorp", "Interested in Q2 rollout"],
      recentActivity: "Visited pricing page 3 times last week",
      dealValue: "$50,000 ARR potential",
    }),
    status: "PENDING",
    priority: 5,
    dueDate: new Date("2025-01-30"),
    sortOrder: 0,
    campaignId: null,
    sendId: null,
    completedAt: null,
    completedById: null,
    skipReason: null,
    organizationId: DEMO_ORG_ID,
    assignedToId: DEMO_USER_ID,
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-20"),
  },
  {
    id: "demo-task-2",
    recipientId: "demo-recipient-2",
    taskType: "HANDWRITTEN_NOTE",
    title: "Write congratulations note for Series A",
    description: "Send a handwritten note congratulating Michael on their recent Series A funding round.",
    context: JSON.stringify({
      talkingPoints: ["Series A company", "50 employees", "CEO & Founder"],
      recentNews: "Announced $12M Series A last month",
      personalNote: "Big coffee fan - mention the coffee gift",
    }),
    status: "PENDING",
    priority: 4,
    dueDate: new Date("2025-01-28"),
    sortOrder: 1,
    campaignId: null,
    sendId: null,
    completedAt: null,
    completedById: null,
    skipReason: null,
    organizationId: DEMO_ORG_ID,
    assignedToId: DEMO_USER_ID,
    createdAt: new Date("2025-01-19"),
    updatedAt: new Date("2025-01-19"),
  },
  {
    id: "demo-task-3",
    recipientId: "demo-recipient-3",
    taskType: "GIFT",
    title: "Send executive gift basket",
    description: "Select and send a premium gift for Emily as a follow-up to the wine tasting experience booking.",
    context: JSON.stringify({
      talkingPoints: ["Director of Procurement", "Looking for gifting solution for 200+ sales reps"],
      preferences: "Enjoys wine and gourmet food",
      dealStage: "Negotiation - $120,000 deal",
    }),
    status: "IN_PROGRESS",
    priority: 5,
    dueDate: new Date("2025-01-29"),
    sortOrder: 2,
    campaignId: null,
    sendId: null,
    completedAt: null,
    completedById: null,
    skipReason: null,
    organizationId: DEMO_ORG_ID,
    assignedToId: DEMO_USER_ID,
    createdAt: new Date("2025-01-18"),
    updatedAt: new Date("2025-01-25"),
  },
  {
    id: "demo-task-4",
    recipientId: "demo-recipient-4",
    taskType: "VIDEO",
    title: "Record product demo video",
    description: "Create a personalized product demo video highlighting features relevant to financial services.",
    context: JSON.stringify({
      talkingPoints: ["Previous customer at old company", "Head of Sales at Finance Plus"],
      industry: "Financial Services",
      compliance: "May need SOC2 documentation",
    }),
    status: "PENDING",
    priority: 3,
    dueDate: new Date("2025-02-01"),
    sortOrder: 3,
    campaignId: null,
    sendId: null,
    completedAt: null,
    completedById: null,
    skipReason: null,
    organizationId: DEMO_ORG_ID,
    assignedToId: DEMO_USER_ID,
    createdAt: new Date("2025-01-21"),
    updatedAt: new Date("2025-01-21"),
  },
  {
    id: "demo-task-5",
    recipientId: "demo-recipient-5",
    taskType: "DIRECT_MAIL",
    title: "Send healthcare case study package",
    description: "Mail printed case study with healthcare-specific ROI data and compliance information.",
    context: JSON.stringify({
      talkingPoints: ["Chief Revenue Officer at MedTech Health", "Healthcare sector - compliance-sensitive"],
      specialRequirements: "Include HIPAA compliance documentation",
      meetingNotes: "Met at healthcare summit",
    }),
    status: "PENDING",
    priority: 4,
    dueDate: new Date("2025-02-03"),
    sortOrder: 4,
    campaignId: null,
    sendId: null,
    completedAt: null,
    completedById: null,
    skipReason: null,
    organizationId: DEMO_ORG_ID,
    assignedToId: DEMO_USER_ID,
    createdAt: new Date("2025-01-22"),
    updatedAt: new Date("2025-01-22"),
  },
  {
    id: "demo-task-6",
    recipientId: "demo-recipient-1",
    taskType: "EXPERIENCE",
    title: "Book team lunch meeting",
    description: "Arrange a team lunch with Sarah and her engineering leads to discuss implementation timeline.",
    context: JSON.stringify({
      talkingPoints: ["Follow-up from earbuds gift", "Discuss Q2 rollout timeline"],
      teamSize: "Engineering team of 45",
      budget: "Up to $500 for team lunch",
    }),
    status: "COMPLETED",
    priority: 5,
    dueDate: null,
    sortOrder: 5,
    campaignId: null,
    sendId: "demo-send-1",
    completedAt: new Date("2025-01-23"),
    completedById: DEMO_USER_ID,
    skipReason: null,
    organizationId: DEMO_ORG_ID,
    assignedToId: DEMO_USER_ID,
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-23"),
  },
];

// Analytics/Stats for Dashboard
export const demoDashboardStats = {
  totalRecipients: 5,
  totalSends: 5,
  totalDelivered: 2,
  totalPending: 2,
  totalSpent: 780.97,
  budgetRemaining: 7849.03,
  deliveryRate: 100, // percentage of shipped that were delivered
  activeCampaigns: 1,
};

// Helper function to get demo data by type
export function getDemoData<T>(type: string): T[] {
  const dataMap: Record<string, unknown[]> = {
    recipients: demoRecipients,
    giftCategories: demoGiftCategories,
    giftItems: demoGiftItems,
    campaigns: demoCampaigns,
    sends: demoSends,
    budgets: demoBudgets,
    activities: demoActivities,
    outreachTasks: demoOutreachTasks,
  };
  return (dataMap[type] || []) as T[];
}

// Helper to find demo item by ID
export function getDemoItemById<T extends { id: string }>(type: string, id: string): T | undefined {
  const data = getDemoData<T>(type);
  return data.find(item => item.id === id);
}
